// <auto-generated />
using CardGame.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CardGame.Domain.Migrations
{
    [DbContext(typeof(CardGameDbContext))]
    [Migration("20200625082918_CardGameTable_AddCardImageColumn")]
    partial class CardGameTable_AddCardImageColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CardGame.Domain.Data.CardNameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardImage");

                    b.Property<string>("CardName");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CardGame");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardImage = "Playing_card_club_A.svg",
                            CardName = "Ace of Clubs"
                        },
                        new
                        {
                            Id = 2,
                            CardImage = "Playing_card_club_2.svg",
                            CardName = "Two of clubs"
                        },
                        new
                        {
                            Id = 3,
                            CardImage = "Playing_card_club_3.svg",
                            CardName = "Three of clubs"
                        },
                        new
                        {
                            Id = 4,
                            CardImage = "Playing_card_club_4.svg",
                            CardName = "Four of clubs"
                        },
                        new
                        {
                            Id = 5,
                            CardImage = "Playing_card_club_5.svg",
                            CardName = "Five of clubs"
                        },
                        new
                        {
                            Id = 6,
                            CardImage = "Playing_card_club_6.svg",
                            CardName = "Six of clubs"
                        },
                        new
                        {
                            Id = 7,
                            CardImage = "Playing_card_club_7.svg",
                            CardName = "Seven of clubs"
                        },
                        new
                        {
                            Id = 8,
                            CardImage = "Playing_card_club_8.svg",
                            CardName = "Eight of clubs"
                        },
                        new
                        {
                            Id = 9,
                            CardImage = "Playing_card_club_9.svg",
                            CardName = "Nine of clubs"
                        },
                        new
                        {
                            Id = 10,
                            CardImage = "Playing_card_club_10.svg",
                            CardName = "Ten of clubs"
                        },
                        new
                        {
                            Id = 11,
                            CardImage = "Playing_card_club_J.svg",
                            CardName = "Jack of clubs"
                        },
                        new
                        {
                            Id = 12,
                            CardImage = "Playing_card_club_Q.svg",
                            CardName = "Queen of clubs"
                        },
                        new
                        {
                            Id = 13,
                            CardImage = "Playing_card_club_K.svg",
                            CardName = "King of clubs"
                        },
                        new
                        {
                            Id = 14,
                            CardImage = "Playing_card_diamond_A.svg",
                            CardName = "Ace of diamonds"
                        },
                        new
                        {
                            Id = 15,
                            CardImage = "Playing_card_diamond_2.svg",
                            CardName = "Two of diamonds"
                        },
                        new
                        {
                            Id = 16,
                            CardImage = "Playing_card_diamond_3.svg",
                            CardName = "Three of diamonds"
                        },
                        new
                        {
                            Id = 17,
                            CardImage = "Playing_card_diamond_4.svg",
                            CardName = "Four of diamonds"
                        },
                        new
                        {
                            Id = 18,
                            CardImage = "Playing_card_diamond_5.svg",
                            CardName = "Five of Diamonds"
                        },
                        new
                        {
                            Id = 19,
                            CardImage = "Playing_card_diamond_6.svg",
                            CardName = "Six of diamonds"
                        },
                        new
                        {
                            Id = 20,
                            CardImage = "Playing_card_diamond_7.svg",
                            CardName = "Seven of diamonds"
                        },
                        new
                        {
                            Id = 21,
                            CardImage = "Playing_card_diamond_8.svg",
                            CardName = "Eight of diamonds"
                        },
                        new
                        {
                            Id = 22,
                            CardImage = "Playing_card_diamond_9.svg",
                            CardName = "Nine of diamonds"
                        },
                        new
                        {
                            Id = 23,
                            CardImage = "Playing_card_diamond_10.svg",
                            CardName = "Ten of diamonds"
                        },
                        new
                        {
                            Id = 24,
                            CardImage = "Playing_card_diamond_J.svg",
                            CardName = "Jack of diamonds"
                        },
                        new
                        {
                            Id = 25,
                            CardImage = "Playing_card_diamond_Q.svg",
                            CardName = "Queen of diamonds"
                        },
                        new
                        {
                            Id = 26,
                            CardImage = "Playing_card_diamond_K.svg",
                            CardName = "King of diamonds"
                        },
                        new
                        {
                            Id = 27,
                            CardImage = "Playing_card_heart_A.svg",
                            CardName = "Ace of hearts"
                        },
                        new
                        {
                            Id = 28,
                            CardImage = "Playing_card_heart_2.svg",
                            CardName = "Two of hearts"
                        },
                        new
                        {
                            Id = 29,
                            CardImage = "Playing_card_heart_3.svg",
                            CardName = "Three of hearts"
                        },
                        new
                        {
                            Id = 30,
                            CardImage = "Playing_card_heart_4.svg",
                            CardName = "Four of hearts"
                        },
                        new
                        {
                            Id = 31,
                            CardImage = "Playing_card_heart_5.svg",
                            CardName = "Five of hearts"
                        },
                        new
                        {
                            Id = 32,
                            CardImage = "Playing_card_heart_6.svg",
                            CardName = "Six of hearts"
                        },
                        new
                        {
                            Id = 33,
                            CardImage = "Playing_card_heart_7.svg",
                            CardName = "Seven of hearts"
                        },
                        new
                        {
                            Id = 34,
                            CardImage = "Playing_card_heart_8.svg",
                            CardName = "Eight of hearts"
                        },
                        new
                        {
                            Id = 35,
                            CardImage = "Playing_card_heart_9.svg",
                            CardName = "Nine of hearts"
                        },
                        new
                        {
                            Id = 36,
                            CardImage = "Playing_card_heart_10.svg",
                            CardName = "Ten of hearts"
                        },
                        new
                        {
                            Id = 37,
                            CardImage = "Playing_card_heart_J.svg",
                            CardName = "Jack of hearts"
                        },
                        new
                        {
                            Id = 38,
                            CardImage = "Playing_card_heart_Q.svg",
                            CardName = "Queen of hearts"
                        },
                        new
                        {
                            Id = 39,
                            CardImage = "Playing_card_heart_K.svg",
                            CardName = "King of hearts"
                        },
                        new
                        {
                            Id = 40,
                            CardImage = "Playing_card_spade_A.svg",
                            CardName = "Ace of spades"
                        },
                        new
                        {
                            Id = 41,
                            CardImage = "Playing_card_spade_2.svg",
                            CardName = "Two of spades"
                        },
                        new
                        {
                            Id = 42,
                            CardImage = "Playing_card_spade_3.svg",
                            CardName = "Three of spades"
                        },
                        new
                        {
                            Id = 43,
                            CardImage = "Playing_card_spade_4.svg",
                            CardName = "Four of spades"
                        },
                        new
                        {
                            Id = 44,
                            CardImage = "Playing_card_spade_5.svg",
                            CardName = "Five of spades"
                        },
                        new
                        {
                            Id = 45,
                            CardImage = "Playing_card_spade_6.svg",
                            CardName = "Six of spades"
                        },
                        new
                        {
                            Id = 46,
                            CardImage = "Playing_card_spade_7.svg",
                            CardName = "Seven of spades"
                        },
                        new
                        {
                            Id = 47,
                            CardImage = "Playing_card_spade_8.svg",
                            CardName = "Eight of spades"
                        },
                        new
                        {
                            Id = 48,
                            CardImage = "Playing_card_spade_9.svg",
                            CardName = "Nine of spades"
                        },
                        new
                        {
                            Id = 49,
                            CardImage = "Playing_card_spade_10.svg",
                            CardName = "Ten of spades"
                        },
                        new
                        {
                            Id = 50,
                            CardImage = "Playing_card_spade_J.svg",
                            CardName = "Jack of spades"
                        },
                        new
                        {
                            Id = 51,
                            CardImage = "Playing_card_spade_Q.svg",
                            CardName = "Queen of spades"
                        },
                        new
                        {
                            Id = 52,
                            CardImage = "Playing_card_spade_K.svg",
                            CardName = "King of spades"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
